<?php
/**
 * Default HTML template for export notifications.
 *
 * Variables made available by the renderer:
 * @var array $event_data          Normalized event payload.
 * @var array $entry_data          History entry data.
 * @var array $job_data            Raw job payload.
 * @var array $context_data        Additional context.
 * @var array $html_paragraphs     Paragraphs generated by the core formatter (HTML).
 * @var array $text_body_paragraphs Paragraphs generated for the plain-text body.
 */

if (!defined('ABSPATH')) {
    exit;
}

$site_name   = isset($event_data['site']['name']) ? esc_html($event_data['site']['name']) : esc_html(get_bloginfo('name'));
$site_url    = isset($event_data['site']['url']) ? esc_url($event_data['site']['url']) : esc_url(home_url());
$result_label = isset($event_data['result_label']) ? esc_html($event_data['result_label']) : esc_html__('Statut inconnu', 'theme-export-jlg');
$completed_at = isset($event_data['completed_at']) ? esc_html($event_data['completed_at']) : '';
$origin_label = isset($event_data['origin_label']) ? esc_html($event_data['origin_label']) : '';
$user_name    = isset($event_data['user']['name']) ? esc_html($event_data['user']['name']) : '';
$duration     = isset($event_data['duration_label']) ? esc_html($event_data['duration_label']) : '';
$size_label   = isset($event_data['size_label']) ? esc_html($event_data['size_label']) : '';
$job_id       = isset($event_data['job_id']) ? esc_html($event_data['job_id']) : '';
$download_url = isset($event_data['persistent_url']) ? esc_url($event_data['persistent_url']) : '';
$summary_url  = isset($event_data['summary_url']) ? esc_url($event_data['summary_url']) : '';
$summary_filename = isset($event_data['summary_filename']) ? esc_html($event_data['summary_filename']) : '';
$language     = get_bloginfo('language');
$language     = $language ? esc_attr($language) : 'fr-FR';
$charset      = get_bloginfo('charset') ?: 'UTF-8';

$exclusion_list = [];

if (!empty($event_data['exclusions']) && is_array($event_data['exclusions'])) {
    foreach ($event_data['exclusions'] as $exclusion) {
        if (!is_scalar($exclusion)) {
            continue;
        }

        $value = trim((string) $exclusion);

        if ('' === $value) {
            continue;
        }

        $exclusion_list[] = esc_html($value);
    }
}

$connector_logs = [];

if (isset($entry_data['remote_connectors']) && is_array($entry_data['remote_connectors'])) {
    foreach ($entry_data['remote_connectors'] as $log) {
        if (!is_array($log)) {
            continue;
        }

        $connector_logs[] = [
            'id'       => isset($log['id']) ? esc_html($log['id']) : '',
            'status'   => isset($log['status']) ? esc_html($log['status']) : '',
            'location' => isset($log['location']) ? esc_html($log['location']) : '',
            'message'  => isset($log['message']) ? esc_html($log['message']) : '',
        ];
    }
}

$primary_color   = '#111827';
$muted_color     = '#6b7280';
$border_color    = '#e5e7eb';
$background      = '#f9fafb';
$card_background = '#ffffff';
$accent_color    = '#2563eb';
?>
<!DOCTYPE html>
<html lang="<?php echo $language; ?>">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=<?php echo esc_attr($charset); ?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><?php echo esc_html(sprintf(__('Rapport d’export — %s', 'theme-export-jlg'), $site_name)); ?></title>
</head>
<body style="margin:0;padding:0;background-color:<?php echo esc_attr($background); ?>;color:<?php echo esc_attr($primary_color); ?>;font-family:'Segoe UI', 'Roboto', 'Helvetica Neue', Arial, sans-serif;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:<?php echo esc_attr($background); ?>;padding:24px 0;">
    <tr>
        <td align="center" style="padding:0 16px;">
            <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px;background-color:<?php echo esc_attr($card_background); ?>;border-radius:12px;overflow:hidden;border:1px solid <?php echo esc_attr($border_color); ?>;">
                <tr>
                    <td style="padding:24px 24px 16px 24px;border-bottom:1px solid <?php echo esc_attr($border_color); ?>;">
                        <p style="margin:0;font-size:14px;line-height:20px;color:<?php echo esc_attr($muted_color); ?>;">
                            <?php echo esc_html($site_name); ?>
                        </p>
                        <h1 style="margin:8px 0 0 0;font-size:22px;line-height:30px;font-weight:600;color:<?php echo esc_attr($primary_color); ?>;">
                            <?php echo esc_html(sprintf(__('Export terminé : %s', 'theme-export-jlg'), $result_label)); ?>
                        </h1>
                        <?php if ('' !== $completed_at) : ?>
                            <p style="margin:8px 0 0 0;font-size:14px;line-height:20px;color:<?php echo esc_attr($muted_color); ?>;">
                                <?php echo esc_html(sprintf(__('Finalisé le %s', 'theme-export-jlg'), $completed_at)); ?>
                            </p>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td style="padding:24px;">
                        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
                            <tbody>
                                <?php if ('' !== $origin_label) : ?>
                                    <tr>
                                        <td style="padding:8px 0;font-size:14px;line-height:20px;color:<?php echo esc_attr($muted_color); ?>;">
                                            <?php esc_html_e('Déclencheur', 'theme-export-jlg'); ?>
                                        </td>
                                        <td style="padding:8px 0;font-size:14px;line-height:20px;text-align:right;color:<?php echo esc_attr($primary_color); ?>;">
                                            <?php echo $origin_label; ?>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                                <?php if ('' !== $user_name) : ?>
                                    <tr>
                                        <td style="padding:8px 0;font-size:14px;line-height:20px;color:<?php echo esc_attr($muted_color); ?>;">
                                            <?php esc_html_e('Initiateur', 'theme-export-jlg'); ?>
                                        </td>
                                        <td style="padding:8px 0;font-size:14px;line-height:20px;text-align:right;color:<?php echo esc_attr($primary_color); ?>;">
                                            <?php echo $user_name; ?>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                                <?php if ('' !== $duration) : ?>
                                    <tr>
                                        <td style="padding:8px 0;font-size:14px;line-height:20px;color:<?php echo esc_attr($muted_color); ?>;">
                                            <?php esc_html_e('Durée', 'theme-export-jlg'); ?>
                                        </td>
                                        <td style="padding:8px 0;font-size:14px;line-height:20px;text-align:right;color:<?php echo esc_attr($primary_color); ?>;">
                                            <?php echo $duration; ?>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                                <?php if ('' !== $size_label) : ?>
                                    <tr>
                                        <td style="padding:8px 0;font-size:14px;line-height:20px;color:<?php echo esc_attr($muted_color); ?>;">
                                            <?php esc_html_e('Taille de l’archive', 'theme-export-jlg'); ?>
                                        </td>
                                        <td style="padding:8px 0;font-size:14px;line-height:20px;text-align:right;color:<?php echo esc_attr($primary_color); ?>;">
                                            <?php echo $size_label; ?>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                                <?php if (!empty($exclusion_list)) : ?>
                                    <tr>
                                        <td style="padding:8px 0;font-size:14px;line-height:20px;color:<?php echo esc_attr($muted_color); ?>;vertical-align:top;">
                                            <?php esc_html_e('Motifs exclus', 'theme-export-jlg'); ?>
                                        </td>
                                        <td style="padding:8px 0;font-size:14px;line-height:20px;text-align:right;color:<?php echo esc_attr($primary_color); ?>;">
                                            <?php echo wp_kses_post(implode('<br />', $exclusion_list)); ?>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                                <?php if ('' !== $job_id) : ?>
                                    <tr>
                                        <td style="padding:8px 0;font-size:14px;line-height:20px;color:<?php echo esc_attr($muted_color); ?>;">
                                            <?php esc_html_e('Identifiant', 'theme-export-jlg'); ?>
                                        </td>
                                        <td style="padding:8px 0;font-size:14px;line-height:20px;text-align:right;color:<?php echo esc_attr($primary_color); ?>;">
                                            <?php echo $job_id; ?>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>

                        <?php if ($download_url) : ?>
                            <p style="margin:24px 0 0 0;text-align:center;">
                                <a href="<?php echo $download_url; ?>" style="display:inline-block;padding:12px 20px;border-radius:8px;background-color:<?php echo esc_attr($accent_color); ?>;color:#ffffff;text-decoration:none;font-weight:600;">
                                    <?php esc_html_e('Télécharger l’archive', 'theme-export-jlg'); ?>
                                </a>
                            </p>
                        <?php endif; ?>

                        <?php if ($summary_url) : ?>
                            <p style="margin:12px 0 0 0;text-align:center;">
                                <a href="<?php echo $summary_url; ?>" style="display:inline-block;padding:10px 18px;border-radius:8px;border:1px solid <?php echo esc_attr($border_color); ?>;color:<?php echo esc_attr($accent_color); ?>;text-decoration:none;font-weight:500;background-color:#ffffff;">
                                    <?php echo esc_html($summary_filename ? sprintf(__('Télécharger %s', 'theme-export-jlg'), $summary_filename) : __('Télécharger le résumé JSON', 'theme-export-jlg')); ?>
                                </a>
                            </p>
                        <?php endif; ?>

                        <?php if (!empty($html_paragraphs) && is_array($html_paragraphs)) : ?>
                            <div style="margin-top:24px;border-top:1px solid <?php echo esc_attr($border_color); ?>;padding-top:16px;">
                                <?php foreach ($html_paragraphs as $paragraph) : ?>
                                    <?php if (!is_scalar($paragraph)) { continue; } ?>
                                    <p style="margin:0 0 12px 0;font-size:14px;line-height:21px;color:<?php echo esc_attr($primary_color); ?>;">
                                        <?php echo wp_kses_post($paragraph); ?>
                                    </p>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>

                        <?php if (!empty($connector_logs)) : ?>
                            <div style="margin-top:24px;border-top:1px solid <?php echo esc_attr($border_color); ?>;padding-top:16px;">
                                <h2 style="margin:0 0 12px 0;font-size:16px;line-height:22px;font-weight:600;color:<?php echo esc_attr($primary_color); ?>;">
                                    <?php esc_html_e('Connecteurs distants', 'theme-export-jlg'); ?>
                                </h2>
                                <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
                                    <thead>
                                        <tr>
                                            <th align="left" style="padding:8px 0;font-size:13px;text-transform:uppercase;letter-spacing:0.04em;color:<?php echo esc_attr($muted_color); ?>;">
                                                <?php esc_html_e('Identifiant', 'theme-export-jlg'); ?>
                                            </th>
                                            <th align="left" style="padding:8px 0;font-size:13px;text-transform:uppercase;letter-spacing:0.04em;color:<?php echo esc_attr($muted_color); ?>;">
                                                <?php esc_html_e('Statut', 'theme-export-jlg'); ?>
                                            </th>
                                            <th align="left" style="padding:8px 0;font-size:13px;text-transform:uppercase;letter-spacing:0.04em;color:<?php echo esc_attr($muted_color); ?>;">
                                                <?php esc_html_e('Destination', 'theme-export-jlg'); ?>
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($connector_logs as $log) : ?>
                                            <tr>
                                                <td style="padding:6px 0;font-size:14px;line-height:20px;color:<?php echo esc_attr($primary_color); ?>;">
                                                    <?php echo $log['id']; ?>
                                                </td>
                                                <td style="padding:6px 0;font-size:14px;line-height:20px;color:<?php echo esc_attr($primary_color); ?>;">
                                                    <?php echo $log['status']; ?>
                                                </td>
                                                <td style="padding:6px 0;font-size:14px;line-height:20px;color:<?php echo esc_attr($primary_color); ?>;">
                                                    <?php echo $log['location']; ?>
                                                    <?php if ('' !== $log['message']) : ?>
                                                        <br /><span style="color:<?php echo esc_attr($muted_color); ?>;font-size:13px;"><?php echo $log['message']; ?></span>
                                                    <?php endif; ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td style="padding:16px 24px;background-color:<?php echo esc_attr($background); ?>;border-top:1px solid <?php echo esc_attr($border_color); ?>;text-align:center;">
                        <p style="margin:0;font-size:12px;line-height:18px;color:<?php echo esc_attr($muted_color); ?>;">
                            <?php echo esc_html(sprintf(__('Site : %s', 'theme-export-jlg'), $site_url)); ?>
                        </p>
                        <p style="margin:4px 0 0 0;font-size:12px;line-height:18px;color:<?php echo esc_attr($muted_color); ?>;">
                            <?php esc_html_e('— Theme Export JLG', 'theme-export-jlg'); ?>
                        </p>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</body>
</html>
